#!/bin/bash
#
# crops a 3D minc volume with world coordinates
#

src=$1
target=$2
extents=($3 $4 $5 $6 $7 $8) # x1 y1 z1 x2 y2 z2
starts=($(worldtovoxel $src ${extents[@]:0:3}))
ends=($(worldtovoxel $src ${extents[@]:3:3}))
length=( $((${ends[0]/.*} - ${starts[0]/.*})) $((${ends[1]/.*} - ${starts[1]/.*})) $((${ends[2]/.*} - ${starts[2]/.*})) )

echo mincreshape -start ${starts[0]/.*},${starts[1]/.*},${starts[2]/.*} -count ${length[0]},${length[1]},${length[2]} $src $target
mincreshape -clobber -start ${starts[0]/.*},${starts[1]/.*},${starts[2]/.*} -count ${length[0]},${length[1]},${length[2]} $src $target
