#!/bin/bash
hosts=penfield,mansfield,franklin,milner,cajaal

function nuc {
  cat sources_* | while read i; do 
		mnc=${i/native/nuc}; 
		mkdir -p $(dirname $mnc); 
		echo $(which nu_correct) \
			$PWD/$i $PWD/${mnc}; 
  done;
}

function talarize {
	while read i; do 
		mnc=${i/native/tal}; 
		mkdir -p $(dirname $mnc); 
		echo $(which mritotal) \
			-model $PWD/icbm_0.3_model/icbm_avg_152_t1_tal_nlin_symmetric_VI_0.3 \
			$PWD/$i $PWD/${mnc/mnc/xfm}; \
	done < sources_0.3 

	while read i; do 
		mnc=${i/native/tal}; 
		mkdir -p $(dirname $mnc); 
		echo $(which mritotal) \
			-model $PWD/icbm_0.9_model/icbm_avg_152_t1_tal_nlin_symmetric_VI_0.9 \
			$PWD/$i $PWD/${mnc/mnc/xfm}; \
	done < sources_0.9 
}

function resample {
  # images
  for i in $PWD/tal/0.3*/*.xfm; do 
    native=${i/tal/native}; 
    echo mincresample -clob -transform $i \
      -like $PWD/icbm_0.3_model/icbm_avg_152_t1_tal_nlin_symmetric_VI_0.3.mnc \
      ${native/.xfm/.mnc} ${i/.xfm/.mnc}; 
    echo mincresample -clob -near -keep -transform $i \
      -like $PWD/icbm_0.3_model/icbm_avg_152_t1_tal_nlin_symmetric_VI_0.3.mnc \
      ${native/.xfm/_labels.mnc} ${i/.xfm/_labels.mnc}; 
  done
  for i in $PWD/tal/0.9_{mb,resampled}/*.xfm; do 
    native=${i/tal/native}; 
    echo mincresample -clob -near -keep -transform $PWD/tal/0.3/$(basename i) \
      -like $PWD/icbm_0.9_model/icbm_avg_152_t1_tal_nlin_symmetric_VI_0.9.mnc \
      ${native/.xfm/.mnc} ${i/.xfm/.mnc}; 
    echo mincresample -clob -near -keep -transform $PWD/tal/0.3/$(basename i) \
      -like $PWD/icbm_0.9_model/icbm_avg_152_t1_tal_nlin_symmetric_VI_0.9.mnc \
      ${native/.xfm/_labels.mnc} ${i/.xfm/_labels.mnc}; 
  done
  for i in $PWD/tal/0.9_{bravo}/*.xfm; do 
    native=${i/tal/native}; 
    echo mincresample -clob -near -keep -transform $i \
      -like $PWD/icbm_0.9_model/icbm_avg_152_t1_tal_nlin_symmetric_VI_0.9.mnc \
      ${native/.xfm/.mnc} ${i/.xfm/.mnc}; 
    echo mincresample -clob -near -keep -transform $i \
      -like $PWD/icbm_0.9_model/icbm_avg_152_t1_tal_nlin_symmetric_VI_0.9.mnc \
      ${native/.xfm/_labels.mnc} ${i/.xfm/_labels.mnc}; 
  done
}

function crop { 
  for i in $PWD/tal/*/*.mnc; do 
    echo $PWD/minccrop $i ${i/.mnc/_cropped.mnc} -50 -75 -60 50 25 40 
  done;
}

function reorder {
  for i in $PWD/tal/*/*_labels_cropped.mnc; do 
    lut="1 1; 101 1; 2 2; 102 2; 4 3; 104 3; 5 4; 105 4; 6 5; 106 5;"
    minclookup -clob -discrete -lut_string "$lut" $i ${i/.mnc/_reordered.mnc};
    #echo reorder_labels.sh $i ${i/.mnc/_reordered.mnc};
  done
}

function slide {
  for i in $PWD/tal/*/jon.mnc; do
    echo $PWD/hippomontage $i ${i/.mnc/_labels.mnc} $(dirname $i)/montage.png
  done
}

function mon {
  montage -fill white -geometry +10+10 -tile 2x2 -background black \
    -label "Winterburn Segmentation (0.3mm-isotropic voxel)" tal/0.3/montage.png \
    -label "Winterburn Resampled (0.9mm-isotropic voxel)"    tal/0.9_resampled/montage.png \
    -label "MAGeT BRAVO (0.9mm-isotropic voxel)"     tal/0.9_bravo/montage.png \
    -label "MAGeT Brain segmentation of Winterburn Resampled" tal/0.9_mb/montage.png \
    -pointsize 28 montage.png
  inkscape --export-pdf=figure.pdf figure.svg
}

$@
